In [49]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [50]:
df = pd.read_csv('transformed_data.csv')

In [51]:
df

,VendorPartNo,Sales Year,Make,Category,IsDevelopment,Total VIO,FirstSoldDate,vehicleMaxQty,PartsAuthority,SSF,Worldpac,PartsAuthority Sales count,SSF Sales count,WorldPac Sales count,UnitsSold360 Sales count,Total Units Sold Sales count,SalesYearRank
0,000 500 0185,2016,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,79.0,0.0,0.0,0.0,109.0,1
1,000 500 0185,2017,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,33.0,0.0,0.0,0.0,225.0,2
2,000 500 0185,2018,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,49.0,0.0,0.0,0.0,371.0,3
3,000 500 0185,2019,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,197.0,0.0,0.0,684.0,521.0,4
4,000 500 0185,2020,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,174.0,0.0,2.0,0.0,478.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23354,ZL-TO1013,2018,Toyota,Engine,0,2345150,2014-10-02,1,0,0,1,0.0,0.0,0.0,0.0,11.0,5
23355,ZL-TO1013,2019,Toyota,Engine,0,2345150,2014-10-02,1,0,0,1,0.0,0.0,363.0,313.0,402.0,6
23356,ZL-TO1013,2020,Toyota,Engine,0,2345150,2014-10-02,1,0,0,1,0.0,0.0,131.0,0.0,239.0,7
23357,ZL-VS1006,2019,Volvo,Engine,0,52689,2020-09-16,1,0,0,0,0.0,0.0,0.0,2.0,0.0,0
23358,ZL-VS1006,2020,Volvo,Engine,0,52689,2020-09-16,1,0,0,0,0.0,0.0,0.0,0.0,2.0,1

In [52]:
df.columns

Index(['VendorPartNo', 'Sales Year', 'Make', 'Category', 'IsDevelopment',
       'Total VIO', 'FirstSoldDate', 'vehicleMaxQty', 'PartsAuthority', 'SSF',
       'Worldpac', 'PartsAuthority Sales count', 'SSF Sales count',
       'WorldPac Sales count', 'UnitsSold360 Sales count',
       'Total Units Sold Sales count', 'SalesYearRank'],
      dtype='object')

In [37]:
# t = df[['Sales Year', 'Make', 'Category', 'IsDevelopment', 'VIO_US',
#        'VIO_CANADA', 'vehicleMaxQty', 'PartsAuthority Sales count', 'SSF Sales count',
#        'WorldPac Sales count', 'UnitsSold360 Sales count',
#        'Total Units Sold Sales count', 'SalesYearRank']].apply(lambda x: x.factorize()[0])
d = df.copy()
d

,VendorPartNo,Sales Year,Make,Category,IsDevelopment,Total VIO,FirstSoldDate,vehicleMaxQty,PartsAuthority,SSF,Worldpac,PartsAuthority Sales count,SSF Sales count,WorldPac Sales count,UnitsSold360 Sales count,Total Units Sold Sales count,SalesYearRank
0,000 500 0185,2016,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,79.0,0.0,0.0,0.0,109.0,1
1,000 500 0185,2017,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,33.0,0.0,0.0,0.0,225.0,2
2,000 500 0185,2018,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,49.0,0.0,0.0,0.0,371.0,3
3,000 500 0185,2019,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,197.0,0.0,0.0,684.0,521.0,4
4,000 500 0185,2020,Mercedes-Benz,Cooling,0,1798416,2016-10-07,1,1,0,1,174.0,0.0,2.0,0.0,478.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23354,ZL-TO1013,2018,Toyota,Engine,0,2345150,2014-10-02,1,0,0,1,0.0,0.0,0.0,0.0,11.0,5
23355,ZL-TO1013,2019,Toyota,Engine,0,2345150,2014-10-02,1,0,0,1,0.0,0.0,363.0,313.0,402.0,6
23356,ZL-TO1013,2020,Toyota,Engine,0,2345150,2014-10-02,1,0,0,1,0.0,0.0,131.0,0.0,239.0,7
23357,ZL-VS1006,2019,Volvo,Engine,0,52689,2020-09-16,1,0,0,0,0.0,0.0,0.0,2.0,0.0,0
23358,ZL-VS1006,2020,Volvo,Engine,0,52689,2020-09-16,1,0,0,0,0.0,0.0,0.0,0.0,2.0,1

In [42]:
x = d[['Make',
        'Total Units Sold Sales count']].apply(lambda x: x.factorize()[0])
x = x.replace(0,np.nan)
x = x.dropna(how='all')
x = x.fillna(0)
x

       Make  Total Units Sold Sales count
1       0.0                           1.0
2       0.0                           2.0
3       0.0                           3.0
4       0.0                           4.0
5       0.0                           5.0
...     ...                           ...
23354  16.0                         147.0
23355  16.0                         712.0
23356  16.0                         274.0
23357   6.0                          52.0
23358   6.0                         265.0

[23345 rows x 2 columns]

In [43]:
chi, pval, dof, exp = chi2_contingency(x)
print(f'Chi-Square: {chi}')
print(f'P-Value: {pval}')
print(f'dof: {dof}')

significance = 0.05

p = 1 - significance
critical_value = chi2.ppf(p, dof)

print('Chi-Square=%.6f, critical value=%.6f\n' % (chi, critical_value))
if chi > critical_value:
    print("""At %.2f level of significance, we reject the null hypotheses and accept H1. 
They are not independent.""" % (significance))
else:
    print("""At %.2f level of significance, we accept the null hypotheses. 
3They are independent.""" % (significance))

Chi-Square: 704964.7211872394
P-Value: 0.0
dof: 23344
Chi-Square=704964.721187, critical value=23700.543595

At 0.05 level of significance, we reject the null hypotheses and accept H1.
They are not independent.